# nagios check runs from NCPA

# CHANGE LOG
# ----------
# 2026-04-06	njeffrey	Script created


# NOTES
# -----

# Reads a text file generated by the MSSQL DBA, alerts on low space reported in text file.
# Sample text file contents:
#ServerName=SQLTEST01; DatabaseName=master; DataGroupName=PRIMARY; TotalMaxSizeMB=999999999; TotalDataMB=4; TotalDataUsedMB=3; TotalDataUsedInternalPct=85; #TotalDataUsedToMaxPct=0                                                                                                    
#ServerName=SQLTEST01; DatabaseName=tempdb; DataGroupName=PRIMARY; TotalMaxSizeMB=1999999998; TotalDataMB=16; TotalDataUsedMB=4; TotalDataUsedInternalPct=30; TotalDataUsedToMaxPct=0                                                                                                  
#ServerName=SQLTEST01; DatabaseName=model; DataGroupName=PRIMARY; TotalMaxSizeMB=999999999; TotalDataMB=8; TotalDataUsedMB=2; TotalDataUsedInternalPct=32; TotalDataUsedToMaxPct=0                                                                                                     
#ServerName=SQLTEST01; DatabaseName=msdb; DataGroupName=PRIMARY; TotalMaxSizeMB=999999999; TotalDataMB=26; TotalDataUsedMB=24; TotalDataUsedInternalPct=92; TotalDataUsedToMaxPct=0                                                                                                    
#ServerName=SQLTEST01; DatabaseName=ReportServer; DataGroupName=PRIMARY; TotalMaxSizeMB=999999999; TotalDataMB=72; TotalDataUsedMB=59; TotalDataUsedInternalPct=82; TotalDataUsedToMaxPct=0                                                                                            
#ServerName=SQLTEST01; DatabaseName=ReportServerTempDB; DataGroupName=PRIMARY; TotalMaxSizeMB=999999999; TotalDataMB=72; TotalDataUsedMB=6; TotalDataUsedInternalPct=8; TotalDataUsedToMaxPct=0                                                                                        



# It is assumed you have a stanza similar to the following on the nagios server services.cfg file:
#define service{
#        ; This check uses NCPA to execute a powershell script on a remote host
#        ; Parameters are --port 5693 --token XXX --metric plugins/plugin_name.ext
#        use                             generic-service
#        host_name                       myserver.example.com
#        service_description             MSSQL DB space
#        check_command                   check_ncpa!5693!MySecretNCPAtoken!plugins/check_mssql_dbspace.ps1
#        contacts                        database_admins    ;who receives the alerts
#        }



<#
.SYNOPSIS
    Nagios check for MSSQL server health metrics exported to text file by DBA

.EXAMPLE
    .\check_mssql_dbspace.ps1
    .\check_mssql_dbspace.ps1 -InputFile C:\ProgramData\nagios\mssql.DatafileFreespace.out -ExcludeDatabase tempdb
#>



param(
    [string]$InputFile,
    [int]$Thresh_Warn  = 85,
    [int]$Thresh_Crit  = 90,
    [int]$TopN = 10,
    [string[]]$ExcludeDatabase = @()
)

# Default input file, used if "-InputFile c:\path\to\file.ext" not provided as command line parameter.
$DefaultInputFile = "C:\ProgramData\nagios\mssql.DatafileFreespace.out"
if (-not $InputFile -or $InputFile.Trim() -eq "") {
    $InputFile = $DefaultInputFile
}

# declare variables
$verbose = "no"   #yes|no flag to increase verbosity for debugging

# Nagios exit codes
$OK       = 0
$WARN     = 1
$CRITICAL = 2
$UNKNOWN  = 3

# show some debug output
if ($verbose -eq "yes") { 
   Write-Output "DEBUG: InputFile=$InputFile" 
   Write-Output "DEBUG: ExcludeDB=$ExcludeDB" 
   Write-Output "DEBUG: WarnThreshold=$Thresh_Warn" 
   Write-Output "DEBUG: CritThreshold=$Thresh_Crit" 
   Write-Output "DEBUG: TopN=$TopN" 
}

# sanity check to confirm values make sense
if ($Thresh_Warn -ge $Thresh_Crit) {
    Write-Output "UNKNOWN - Warning threshold $Thresh_Warn must be less than Critical threshold $Thresh_Crit"
    exit $UNKNOWN
}

# Ensure parent directory of $InputFile exists
try {
    $InputDir = Split-Path -Path $InputFile -Parent
    if (-not (Test-Path -LiteralPath $InputDir -PathType Container)) {
        New-Item -ItemType Directory -Path $InputDir -Force -ErrorAction Stop | Out-Null
    }
}
catch {
    Write-Output "UNKNOWN - Failed to create/access directory: $InputDir : $($_.Exception.Message)"
    exit $UNKNOWN
}


# Confirm the $InputFile exists
if (-not (Test-Path -LiteralPath $InputFile -PathType Leaf)) {
    Write-Output "UNKNOWN - Input file not found: $InputFile"
    exit $UNKNOWN
}


# Check file age of $InputFile to ensure it is not outdated (stale data protection)
# Assume the DBA runs their SQL maintenance job hourly, so alert if file is more than 120 minutes old
# This gives enough time for the file to be recreated even if there was a reboot when the job was supposed to run.
$MaxAgeMinutes = 120
if ($verbose -eq "yes") { Write-Output "DEBUG: MaxAgeMinutes=$MaxAgeMinutes" }
try {
    $FileInfo = Get-Item -LiteralPath $InputFile -ErrorAction Stop
}
catch {
    Write-Output "UNKNOWN - Unable to stat file: $InputFile : $($_.Exception.Message)"
    exit $UNKNOWN
}
$AgeMinutes = (New-TimeSpan -Start $FileInfo.LastWriteTime -End (Get-Date)).TotalMinutes
if ($verbose -eq "yes") { Write-Output "DEBUG: InputFile $InputFile age in minutes: $AgeMinutes" }
if ($AgeMinutes -gt $MaxAgeMinutes) {
    Write-Output ("CRITICAL - Input file is stale ({0:N1} minutes old, threshold={1}) : {2}" -f $AgeMinutes, $MaxAgeMinutes, $InputFile)
    exit $CRITICAL
}

# open $InputFile for reading
try {
    $Lines = Get-Content -LiteralPath $InputFile -ErrorAction Stop | Where-Object { $_.Trim() -ne "" }
}
catch {
    Write-Output "UNKNOWN - Failed to read input file $InputFile : $($_.Exception.Message)"
    exit $UNKNOWN
}

if (-not $Lines -or $Lines.Count -eq 0) {
    Write-Output "UNKNOWN - Input file is empty: $InputFile"
    exit $UNKNOWN
}

# Normalize exclusion list to lowercase
$ExcludeSet = $ExcludeDatabase | ForEach-Object { $_.ToLower() }

$Records = @()

foreach ($Line in $Lines) {
    $Fields = @{}

    foreach ($Pair in ($Line -split ';')) {
        $Pair = $Pair.Trim()
        if ($Pair -eq '') { continue }

        $NameValue = $Pair -split '=', 2
        if ($NameValue.Count -ne 2) { continue }

        $Key = $NameValue[0].Trim()
        $Value = $NameValue[1].Trim()
        $Fields[$Key] = $Value
    }

    $RequiredFields = @(
        'ServerName',
        'DatabaseName',
        'DataGroupName',
        'TotalMaxSizeMB',
        'TotalDataMB',
        'TotalDataUsedMB',
        'TotalDataUsedToMaxPct'
    )

    $Missing = $RequiredFields | Where-Object { -not $Fields.ContainsKey($_) }
    if ($Missing.Count -gt 0) {
        Write-Output "UNKNOWN - Invalid line in input file, missing fields: $($Missing -join ', ') ; line='$Line'"
        exit $UNKNOWN
    }

    try {
        $ServerName = $Fields['ServerName']
        $DBName     = $Fields['DatabaseName']

        # Apply exclusion filter
        if ($ExcludeSet -contains $DBName.ToLower()) {
            continue
        }

        $Record = [PSCustomObject]@{
            DatabaseName          = $DBName
            ServerName            = $Fields['ServerName']
            DataGroupName         = $Fields['DataGroupName']
            TotalMaxSizeMB        = [int64]$Fields['TotalMaxSizeMB']
            TotalDataMB           = [int64]$Fields['TotalDataMB']
            TotalDataUsedMB       = [int64]$Fields['TotalDataUsedMB']
            TotalDataUsedToMaxPct = [int]$Fields['TotalDataUsedToMaxPct']
        }
        $Records += $Record
    }
    catch {
        Write-Output "UNKNOWN - Failed to parse numeric values from line: '$Line'"
        exit $UNKNOWN
    }
}

if ($Records.Count -eq 0) {
    Write-Output "UNKNOWN - No valid records after filtering (all excluded or invalid)"
    exit $UNKNOWN
}

$CriticalRecords = $Records | Where-Object { $_.TotalDataUsedToMaxPct -ge $Thresh_Crit }
$WarningRecords  = $Records | Where-Object { $_.TotalDataUsedToMaxPct -ge $Thresh_Warn -and $_.TotalDataUsedToMaxPct -lt $Thresh_Crit }

$Sorted = $Records | Sort-Object TotalDataUsedToMaxPct -Descending
$TopRecords = $Sorted | Select-Object -First $TopN

$SummaryParts = @()
$PerfParts = @()

foreach ($Record in $TopRecords) {
    $Key = "$($Record.DatabaseName).$($Record.DataGroupName)"
    $SummaryParts += "$Key=$($Record.TotalDataUsedToMaxPct)%($($Record.TotalDataUsedMB)/$($Record.TotalMaxSizeMB)MB)"

    $SafeLabel = ($Key -replace '[^A-Za-z0-9_]', '_')
    $PerfParts += "dbusedtomaxpct_${SafeLabel}=$($Record.TotalDataUsedToMaxPct)%;$Thresh_Warn;$Thresh_Crit;0;100"
}

# format the data to be used in the message body and nagios performance data
$Summary  = $SummaryParts -join ', '
$PerfData = $PerfParts    -join ' '

if ($CriticalRecords.Count -gt 0) {
    Write-Output "CRITICAL - MSSQL dbspace TotalDataUsedToMaxPct >= $Thresh_Crit on $($CriticalRecords.Count) filegroup(s). ServerName=$ServerName Databases=$($Records.Count). $Summary | $PerfData"
    exit $CRITICAL
}
elseif ($WarningRecords.Count -gt 0) {
    Write-Output "WARNING - MSSQL dbspace TotalDataUsedToMaxPct >= $Thresh_Warn on $($WarningRecords.Count) filegroup(s). ServerName=$ServerName Databases=$($Records.Count). $Summary | $PerfData"
    exit $WARN
}
else {
    Write-Output "OK - MSSQL dbspace TotalDataUsedToMaxPct within thresholds. ServerName=$ServerName Databases=$($Records.Count). $Summary | $PerfData"
    exit $OK
}
